[Unit]
ConditionFirmware=|device-tree-compatible(chargebyte,imx93-charge-som)
ConditionFirmware=|device-tree-compatible(chargebyte,imx93-charge-control-y)
ConditionFirmware=|device-tree-compatible(chargebyte,imx93-lime)
ConditionFirmware=|device-tree-compatible(chargebyte,imx93-protolime)
