[Unit]
ConditionFirmware=|device-tree-compatible(chargebyte,imx93-charge-control-v)
ConditionFirmware=|device-tree-compatible(chargebyte,imx93-lime)
ConditionFirmware=|device-tree-compatible(chargebyte,imx93-protolime)
